### ISSUE TITLE
Error with gm/convert binaries

### ISSUE THREAD

**Issue by axul** [disusered/cordova-icon-gm#2]
**Platform:** macOS sierra
**What I did:** 
1. npm install -g cordova-icon-gm
**Log:**
Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "icon.png" "-resize" "40x40" "platforms/ios/Programa experto en interpretación de espirometrías/Resources/icons/icon-40.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/axul/.nvm/versions/node/v7.1.0/lib/node_modules/cordova-icon-gm/node_modules/gm/lib/command.js:232:12)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Then i tried:**

1. npm install -g gm
2. npm install -g cordova-icon-gm

Same result

**Comment by glennra** [comment]
You need to install GraphicsMagick separately. You can use Brew or MacPorts for this.
