### ISSUE TITLE
Doesn't create icon directories

### ISSUE THREAD

**Issue by glennra** [disusered/cordova-icon-gm#3]
With cordova 7.0.1 when running  'cordova platform add ios' I get the following error:

```
Checking Project & Icon

  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

{ Error: Command failed: gm convert: Unable to open file (platforms/ios/myApp/Resources/icons/icon-small@2x.png) [No such file or directory].

    at ChildProcess.onExit (/path/to/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) code: 1, signal: null }

```
If I manually create the directory `platforms/ios/myApp/Resources/icons` and all the subsequent directories that it fails on then the command eventually succeeds.

**Comment by disusered** [comment]
Thanks for the feedback, I'll take a look tomorrow afternoon!

**Comment by hperrin** [comment]
Same thing here.

```
Saving android@~7.1.0 into config.xml file ...

 Checking Project & Icon

{ msg: 'starting icon build' }
  ✓  platforms found: ios, android
  ✓  icon.png exists
  ✓  config.xml exists

 Generating Icons for ios

Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "icon.png" "-resize" "40x40" "platforms/ios/Tunnelgram/Resources/icons/icon-40.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (/Users/hperrin/repos/tunnelgram/cordova/node_modules/gm/lib/command.js:232:12)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

And with the splash script.

```
Saving android@~7.1.0 into config.xml file ...

 Checking Project & Splashscreens

  ✓  platforms found: ios, android
  ✓  splash.png exists
  ✓  config.xml exists

 Generating splash screens for ios

Error: ENOENT: no such file or directory, open 'platforms/ios/Tunnelgram/Resources/splash/Default~iphone.png'
```
